import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import CosmicBackground from "./components/CosmicBackground";
import BackgroundMusic from "./components/BackgroundMusic";

export const metadata = {
  title: "Galaxy Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ height: "100%", fontFamily: 'Audiowide, Arial, Helvetica, sans-serif' }}>
      <body
        className="antialiased min-h-screen flex flex-col"
        style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}
      >
        <CosmicBackground />
        <Header />
        <div style={{ flex: 1, display: "flex", flexDirection: "column" }}>
          {children}
        </div>
        <Footer />
        <BackgroundMusic />
      </body>
    </html>
  );
}
